### ISSUE TITLE
No "roles" claim defined in the initial JWT on "Sign Up" only

### ISSUE THREAD

**Issue by DanailMinchev** [auth0-samples/auth0-spring-security-api-client-samples#1]
Hi @arcseldon,

I noticed in my tests with other examples like https://github.com/auth0/auth0-ionic2 and https://github.com/auth0/auth0-angular2 and in this example repo as well that on initial "Sign Up" the JWT `id_token` which is returned does not have "`roles`" claim in it.

JWT payload example returned after successful sign up:
```
{
  "user_id": "auth0|zzz",
  "name": "user@email.com",
  "nickname": "user",
  "email": "user@email.com",
  "email_verified": false,
  "picture": "https://s.gravatar.com/avatar/zzzz?s=480&r=pg&d=https%3A%2F%2Fcdn.auth0.com%2Favatars%2Fda.png",
  "iss": "https://domain.eu.auth0.com/",
  "sub": "auth0|zzz",
  "aud": "zzzz",
  "exp": 1466648934,
  "iat": 1466612934
}
```

So, the api calls failed to execute (error `403`).

After second login, the `roles` are there and api calls succeed.

Seems like a bug in `Auth0 Lock` or maybe we need to change the `Rules` to apply on `Sign Up` as well.

Currently I am doing research about the `Rules`.

I was not sure where to submit the issue and decided to paste it here (as you are very responsive).
I can try to paste it on other places, but need to do the `Rules` research and confirm if it's `Lock` bug.

Thanks!

**Comment by arcseldon** [comment]
@DanailMinchev - thanks for raising this. Believe what you have discovered is that Rules are activated by different `stages`. The signup process actually comes under user_registration stage. See [here](https://auth0.com/docs/api/management/v2#!/Rules/post_rules)  - you can use that page to create a rule and assign it the `user_registration` stage. You want something similar to:

```
curl -H "Authorization: Bearer {{YOUR MANAGEMENT API TOKEN}}" -X POST  -H "Content-Type: application/json" -d '{"name":"set roles to a user for registration","script":"function (user, context, callback) { if (context.clientID !== 'eTQbNn3qxypLq2Lc1qQEThYL6R7M7MDh') { return callback(null, user, context); } user.app_metadata = user.app_metadata || {}; var addRolesToUser = function(user, cb) { cb(null, ['ROLE_ADMIN']); }; addRolesToUser(user, function(err, roles) { if (err) { callback(err); } else { user.app_metadata.roles = roles; auth0.users.updateAppMetadata(user.user_id, user.app_metadata).then(function(){ callback(null, user, context); }) .catch(function(err){ callback(err); }); } }); }","enabled":true,"stage":"user_registration"}' https://{{YOUR_TENANT}}.auth0.com/api/v2/rules
```

I generated the CURL request from the link provided above. It looks a lot more complicated than it really is but still, this is not a great user experience i am afraid. Please let me know how you get on.

**Comment by DanailMinchev** [comment]
I am receiving `500 Internal Server Error` on SignUp
I am not sure if I've generated the `{{YOUR MANAGEMENT API TOKEN}}` properly.
![management api v2](https://cloud.githubusercontent.com/assets/7883702/16278943/b528ad58-38b0-11e6-921b-97e91afc70af.png)

After executing I received following response:
```
{
  "id": "rul_vktA6A4QpyFwS6ys",
  "enabled": true,
  "script": "function (user, context, callback) { if (context.clientID !== rZA3JHqx3DfdsCH1EXNjRFrl9m72rncZ) { return callback(null, user, context); } user.app_metadata = user.app_metadata || {}; var addRolesToUser = function(user, cb) { cb(null, [ROLE_ADMIN]); }; addRolesToUser(user, function(err, roles) { if (err) { callback(err); } else { user.app_metadata.roles = roles; auth0.users.updateAppMetadata(user.user_id, user.app_metadata).then(function(){ callback(null, user, context); }) .catch(function(err){ callback(err); }); } }); }",
  "name": "set roles to a user for registration",
  "order": 1,
  "stage": "user_registration"
}
```

**Comment by DanailMinchev** [comment]
Maybe the error is that the client id is not a string? I copied & pasted without `''`.
I will try to delete the rule and test again. Sorry

**Comment by arcseldon** [comment]
@DanailMinchev - yes, it looks like the Rule was successfully created, but the server does not like something about the payload and is dying when executed. You created the management token correctly though.  Try deleting the [Rule](https://auth0.com/docs/api/management/v2#!/Rules/delete_rules_by_id) passing in your rule id above: `rul_vktA6A4QpyFwS6y`.

what i suggest you do is dumb the rule down to bare minimum and see if signup works (literally just an empty callback vanilla rule) - then try adding to the rule and re-executing. LIke i say, not a fan of how we have no dashboard support for this.

**Comment by DanailMinchev** [comment]
I tried to delete the rule:

```
curl -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJHNmpETUVITmxwR1R6N1ZSVGZzSlZmRXBvVWxSdEZMTyIsInNjb3BlcyI6eyJydWxlcyI6eyJhY3Rpb25zIjpbImRlbGV0ZSIsImNyZWF0ZSIsInJlYWQiLCJ1cGRhdGUiXX19LCJpYXQiOjE0NjY2MjExMzksImp0aSI6ImY1MzdiYmRlY2JjM2I2NWUzOTU1ZmFiNGRhMGIzMGU4In0.sWqtdA8xVAS1tq4sfvLindXArfXxMnbDoC9c1f4QDUM" -X DELETE  https://user.eu.auth0.com/api/v2/rules/rul_vktA6A4QpyFwS6y

"statusCode":400,"error":"Bad Request","message":"Path validation error: 'String does not match pattern ^rul_[A-Za-z0-9]{16}$: rul_vktA6A4QpyFwS6y' on property id (The id of the rule to delete).","errorCode":"invalid_uri"}
```

**Comment by arcseldon** [comment]
@DanailMinchev - try deleting using the Management API page itself - just hit `try` after adding your id to the form and giving delete permission to management token.

btw - this might interest you - [SPA sample for API Server](https://github.com/auth0-samples/auth0-spring-security-api-client-samples) - wrote it yesterday.  am awaiting confirmation latest maven versions were published as i had to slightly modify the underlying library to get CORS to behave for SPA.

**Comment by arcseldon** [comment]
sorry, it is 4 am here. shall be online am.

**Comment by DanailMinchev** [comment]
@arcseldon 

I managed to delete the rule using Management API https://auth0.com/docs/api/management/v2

Also I tried to create new "blank" rule:

cURL:
```
curl -H "Authorization: Bearer eyJhbGciOiJIUzI1NiI.....sInR5c1f4QDUM" -X POST  -H "Content-Type: application/json" -d '{"enabled":true,"script":"function (user, context, callback) { callback(null, user, context); }","name":"set roles to a user for registration","stage":"user_registration"}' https://user.eu.auth0.com/api/v2/rules
```

Response:
```
{
  "id": "rul_gu80l2ueQdoczqxO",
  "enabled": true,
  "script": "function (user, context, callback) { callback(null, user, context); }",
  "name": "set roles to a user for registration",
  "order": 1,
  "stage": "user_registration"
}
```

When trying to login using https://github.com/auth0-samples/auth0-spring-security-api-client-samples/tree/master/auth0-spring-security-api-angular-client example I am still receiving `Error 500`

It is NOT urgent now :) - I appreciate your help.

**Comment by arcseldon** [comment]
@DanailMinchev - fyi - have updated this repo. The sample can now do `delegation` so if you want (optional) your SPA app and API server can be using differrent Auth0 applications. See updated README for details.

Yep, sorry to hear you are experiencing trouble with the `user_registration` stage rule. will check with our team internally.

**Comment by arcseldon** [comment]
@DanailMinchev - running the sample provided for `create rule` does appear to be successful. 

![manapi](https://cloud.githubusercontent.com/assets/2599332/16309382/7f027cec-39a3-11e6-8044-3cb2830ce83f.jpg)

So think it is just a case of being very careful with the escaping when you create and publish the rule.  Perhaps easiest is to setup a `create rule` / `getRules` (to find id) and `deleteRule` in POSTMAN - then keep experimenting until you get syntax that doesn't break. Re-iterate, we need a GUI for the management of this in Dashboard, but this would be a workaround. Make sense?  Let me know if you get really stuck.

**Comment by DanailMinchev** [comment]
@arcseldon 

I was experimenting with "Management API" and also cURL.

After few tests, now I have following situation:
- No rules are returned in response for `/api/v2/rules` - blank array `[]` is returned
```
curl -H "Authorization: Bearer eXXXg" https://edease.eu.auth0.com/api/v2/rules

[]
```
- `Error 500` is returned on sign-up using `Lock` client

Basically, I cannot find the id of the rule to delete it and continue the experiment / my tests.
Also if I manage to create this workaround - it is not documented and I think other devs will have the same problem - if it is official solution please let me know / document it.
Well tested `cURL` example will be great to have in the documentation (I cannot test because of the issue described above).

IMHO the `Management API` dashboard should handle escaping or even the server side should not process creation of problematic (with wrong syntax) rules.

Thanks

**Comment by DanailMinchev** [comment]
I closed this issue, because the client wants me to look for another solutions (as there are problems with other issues like: https://github.com/auth0/auth0-ionic2/issues/11) and probably I will not have time to respond.

I can continue if the client decides to go back with `Auth0`.

Thank you for your support, I really appreciate it!

**Comment by arcseldon** [comment]
@DanailMinchev - are you on Skype?  Will contact you directly via email. Pretty sure we can iron your issues v.quickly - let me know if you can spare 30 mins & we can get to a resolution for you.

**Comment by Hildebrand** [comment]
I'm trying to get this to work as well.

Using the sample code that's available online I've been able to set up the rule in the `user_registration` stage:
```
function(user, context, callback){
  user.app_metadata = user.app_metadata || {};
  user.app_metadata.roles = user.app_metadata.roles || [];
  user.app_metadata.roles.push('ROLE_USER');
  auth0.users.updateAppMetadata(user.user_id, user.app_metadata)
    .then(function(){
      callback(null, user, context);
    })
    .catch(function(err){
      callback(err);
    });
}
```

 When doing the actual sign up however, rule execution fails with the following error:
`{"message":"auth0 is not defined","fromSandbox":true}`

Is this scope not available in the user_registration stage? Am I doing something wrong?

**Comment by Hildebrand** [comment]
I got to solve this with help of Auth0 support.
Above method, of using rules, has been superseded by the use of hooks. To accomplish above, specify the following hook:

```
module.exports = function (user, context, cb) {
  var response = {};

  response.user = {
    user_metadata: {},
    app_metadata: {
      roles: ["ROLE_USER"]
    }
  };

  cb(null, response);
};
```
